version: '3.2'
services:
  frontend:
    build: .
    environment:
       - CHOKIDAR_USEPOLLING=true
    env_file: .env
    ports:
      - '3030:3030'
    command: npm run dev
    volumes:
      - /frontend/node_modules
      - .:/frontend